
# pma -m 25000 pfmodel1
# 41 states, 92 transitions, 1 accepting states, 0 unsafe states, 0 finished and 0 deadend states

# actions here are just labels, but must be symbols with __name__ attribute

def create_broadcast(): pass
def activate_broadcast(): pass
def delete_broadcast(): pass

# states, key of each state here is its number in graph etc. below

states = {
  0 : {'pfmodel1': {'Broadcasts': []}},
  1 : {'pfmodel1': {'Broadcasts': [['brd-0', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  2 : {'pfmodel1': {'Broadcasts': [['brd-0', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  3 : {'pfmodel1': {'Broadcasts': [['brd-1', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  4 : {'pfmodel1': {'Broadcasts': [['brd-1', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  5 : {'pfmodel1': {'Broadcasts': [['brd-0', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  6 : {'pfmodel1': {'Broadcasts': [['brd-0', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  7 : {'pfmodel1': {'Broadcasts': [['brd-0', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  8 : {'pfmodel1': {'Broadcasts': [['brd-0', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  9 : {'pfmodel1': {'Broadcasts': [['brd-0', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  10 : {'pfmodel1': {'Broadcasts': [['brd-0', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  11 : {'pfmodel1': {'Broadcasts': [['brd-1', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  12 : {'pfmodel1': {'Broadcasts': [['brd-1', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  13 : {'pfmodel1': {'Broadcasts': [['brd-1', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  14 : {'pfmodel1': {'Broadcasts': [['brd-1', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  15 : {'pfmodel1': {'Broadcasts': [['brd-1', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  16 : {'pfmodel1': {'Broadcasts': [['brd-1', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  17 : {'pfmodel1': {'Broadcasts': [['brd-0', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  18 : {'pfmodel1': {'Broadcasts': [['brd-0', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  19 : {'pfmodel1': {'Broadcasts': [['brd-0', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  20 : {'pfmodel1': {'Broadcasts': [['brd-0', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  21 : {'pfmodel1': {'Broadcasts': [['brd-0', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  22 : {'pfmodel1': {'Broadcasts': [['brd-0', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  23 : {'pfmodel1': {'Broadcasts': [['brd-0', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  24 : {'pfmodel1': {'Broadcasts': [['brd-0', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  25 : {'pfmodel1': {'Broadcasts': [['brd-1', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  26 : {'pfmodel1': {'Broadcasts': [['brd-1', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  27 : {'pfmodel1': {'Broadcasts': [['brd-1', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  28 : {'pfmodel1': {'Broadcasts': [['brd-1', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  29 : {'pfmodel1': {'Broadcasts': [['brd-1', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'created', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  30 : {'pfmodel1': {'Broadcasts': [['brd-1', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  31 : {'pfmodel1': {'Broadcasts': [['brd-1', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  32 : {'pfmodel1': {'Broadcasts': [['brd-1', 'created', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  33 : {'pfmodel1': {'Broadcasts': [['brd-0', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  34 : {'pfmodel1': {'Broadcasts': [['brd-0', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  35 : {'pfmodel1': {'Broadcasts': [['brd-0', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  36 : {'pfmodel1': {'Broadcasts': [['brd-0', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-1', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  37 : {'pfmodel1': {'Broadcasts': [['brd-1', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  38 : {'pfmodel1': {'Broadcasts': [['brd-1', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
  39 : {'pfmodel1': {'Broadcasts': [['brd-1', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'activated', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8']]}},
  40 : {'pfmodel1': {'Broadcasts': [['brd-1', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'], ['brd-0', 'activated', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8']]}},
}

# initial state, accepting states, unsafe states, frontier states, deadend states

initial = 0
accepting = [0]
unsafe = []
frontier = []
finished = []
deadend = []
runstarts = [0]

# finite state machine, list of tuples: (current, (action, args, result), next)

graph = (
  (0, (create_broadcast, ('brd-0', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'), None), 1),
  (0, (create_broadcast, ('brd-0', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'), None), 2),
  (0, (create_broadcast, ('brd-1', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'), None), 3),
  (0, (create_broadcast, ('brd-1', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'), None), 4),
  (1, (create_broadcast, ('brd-1', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'), None), 5),
  (1, (create_broadcast, ('brd-1', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'), None), 6),
  (1, (activate_broadcast, ('brd-0',), None), 7),
  (2, (create_broadcast, ('brd-1', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'), None), 8),
  (2, (create_broadcast, ('brd-1', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'), None), 9),
  (2, (activate_broadcast, ('brd-0',), None), 10),
  (3, (activate_broadcast, ('brd-1',), None), 11),
  (3, (create_broadcast, ('brd-0', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'), None), 12),
  (3, (create_broadcast, ('brd-0', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'), None), 13),
  (4, (activate_broadcast, ('brd-1',), None), 14),
  (4, (create_broadcast, ('brd-0', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'), None), 15),
  (4, (create_broadcast, ('brd-0', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'), None), 16),
  (5, (activate_broadcast, ('brd-1',), None), 17),
  (5, (activate_broadcast, ('brd-0',), None), 18),
  (6, (activate_broadcast, ('brd-1',), None), 19),
  (6, (activate_broadcast, ('brd-0',), None), 20),
  (7, (create_broadcast, ('brd-1', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'), None), 18),
  (7, (create_broadcast, ('brd-1', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'), None), 20),
  (7, (delete_broadcast, ('brd-0',), None), 0),
  (8, (activate_broadcast, ('brd-1',), None), 21),
  (8, (activate_broadcast, ('brd-0',), None), 22),
  (9, (activate_broadcast, ('brd-1',), None), 23),
  (9, (activate_broadcast, ('brd-0',), None), 24),
  (10, (create_broadcast, ('brd-1', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'), None), 22),
  (10, (create_broadcast, ('brd-1', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'), None), 24),
  (10, (delete_broadcast, ('brd-0',), None), 0),
  (11, (delete_broadcast, ('brd-1',), None), 0),
  (11, (create_broadcast, ('brd-0', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'), None), 25),
  (11, (create_broadcast, ('brd-0', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'), None), 26),
  (12, (activate_broadcast, ('brd-1',), None), 25),
  (12, (activate_broadcast, ('brd-0',), None), 27),
  (13, (activate_broadcast, ('brd-1',), None), 26),
  (13, (activate_broadcast, ('brd-0',), None), 28),
  (14, (delete_broadcast, ('brd-1',), None), 0),
  (14, (create_broadcast, ('brd-0', 'audiencevne-ZL-PFE-03', 'http://media.blacktrash.org/stsp.m3u8'), None), 29),
  (14, (create_broadcast, ('brd-0', 'audiencevne-ZL-PFE-04', 'http://media.blacktrash.org/stsp.m3u8'), None), 30),
  (15, (activate_broadcast, ('brd-1',), None), 29),
  (15, (activate_broadcast, ('brd-0',), None), 31),
  (16, (activate_broadcast, ('brd-1',), None), 30),
  (16, (activate_broadcast, ('brd-0',), None), 32),
  (17, (delete_broadcast, ('brd-1',), None), 1),
  (17, (activate_broadcast, ('brd-0',), None), 33),
  (18, (activate_broadcast, ('brd-1',), None), 33),
  (18, (delete_broadcast, ('brd-0',), None), 4),
  (19, (delete_broadcast, ('brd-1',), None), 1),
  (19, (activate_broadcast, ('brd-0',), None), 34),
  (20, (activate_broadcast, ('brd-1',), None), 34),
  (20, (delete_broadcast, ('brd-0',), None), 3),
  (21, (delete_broadcast, ('brd-1',), None), 2),
  (21, (activate_broadcast, ('brd-0',), None), 35),
  (22, (activate_broadcast, ('brd-1',), None), 35),
  (22, (delete_broadcast, ('brd-0',), None), 4),
  (23, (delete_broadcast, ('brd-1',), None), 2),
  (23, (activate_broadcast, ('brd-0',), None), 36),
  (24, (activate_broadcast, ('brd-1',), None), 36),
  (24, (delete_broadcast, ('brd-0',), None), 3),
  (25, (delete_broadcast, ('brd-1',), None), 1),
  (25, (activate_broadcast, ('brd-0',), None), 37),
  (26, (delete_broadcast, ('brd-1',), None), 2),
  (26, (activate_broadcast, ('brd-0',), None), 38),
  (27, (activate_broadcast, ('brd-1',), None), 37),
  (27, (delete_broadcast, ('brd-0',), None), 3),
  (28, (activate_broadcast, ('brd-1',), None), 38),
  (28, (delete_broadcast, ('brd-0',), None), 3),
  (29, (delete_broadcast, ('brd-1',), None), 1),
  (29, (activate_broadcast, ('brd-0',), None), 39),
  (30, (delete_broadcast, ('brd-1',), None), 2),
  (30, (activate_broadcast, ('brd-0',), None), 40),
  (31, (activate_broadcast, ('brd-1',), None), 39),
  (31, (delete_broadcast, ('brd-0',), None), 4),
  (32, (activate_broadcast, ('brd-1',), None), 40),
  (32, (delete_broadcast, ('brd-0',), None), 4),
  (33, (delete_broadcast, ('brd-1',), None), 7),
  (33, (delete_broadcast, ('brd-0',), None), 14),
  (34, (delete_broadcast, ('brd-1',), None), 7),
  (34, (delete_broadcast, ('brd-0',), None), 11),
  (35, (delete_broadcast, ('brd-1',), None), 10),
  (35, (delete_broadcast, ('brd-0',), None), 14),
  (36, (delete_broadcast, ('brd-1',), None), 10),
  (36, (delete_broadcast, ('brd-0',), None), 11),
  (37, (delete_broadcast, ('brd-1',), None), 7),
  (37, (delete_broadcast, ('brd-0',), None), 11),
  (38, (delete_broadcast, ('brd-1',), None), 10),
  (38, (delete_broadcast, ('brd-0',), None), 11),
  (39, (delete_broadcast, ('brd-1',), None), 7),
  (39, (delete_broadcast, ('brd-0',), None), 14),
  (40, (delete_broadcast, ('brd-1',), None), 10),
  (40, (delete_broadcast, ('brd-0',), None), 14),
)
